// <auto-generated />
using VILLAGEBANKING.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VILLAGEBANKING.Migrations.GroupDB
{
    [DbContext(typeof(GroupDBContext))]
    [Migration("20220328072131_Groups")]
    partial class Groups
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VILLAGEBANKING.Models.GroupModel", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"), 1L, 1);

                    b.Property<int>("FrequencyOfContributions")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoanEligibleAmountId")
                        .HasColumnType("int");

                    b.Property<double>("LoanRate")
                        .HasColumnType("float");

                    b.Property<double>("MinimumContributionAmount")
                        .HasColumnType("float");

                    b.Property<double>("PenaltyFee")
                        .HasColumnType("float");

                    b.Property<double>("ProvisionalInterest")
                        .HasColumnType("float");

                    b.HasKey("GroupId");

                    b.HasIndex("LoanEligibleAmountId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("VILLAGEBANKING.Models.LoanEligibilityModel", b =>
                {
                    b.Property<int>("LoanEligibleAmountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanEligibleAmountId"), 1L, 1);

                    b.Property<int>("AmountContribution")
                        .HasColumnType("int");

                    b.Property<int>("EligibleLoanAmount")
                        .HasColumnType("int");

                    b.HasKey("LoanEligibleAmountId");

                    b.ToTable("LoanEligibilityModel");
                });

            modelBuilder.Entity("VILLAGEBANKING.Models.GroupModel", b =>
                {
                    b.HasOne("VILLAGEBANKING.Models.LoanEligibilityModel", "LoanEligibility")
                        .WithMany()
                        .HasForeignKey("LoanEligibleAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanEligibility");
                });
#pragma warning restore 612, 618
        }
    }
}
